# Header
menu:
  - title: Home
    url: /
    icon: home
  - title: Archives
    url: /archives
    icon: archive
  - title: About
    url: /about
    icon: info
  - title: RSS
    url: /atom.xml
    icon: bookmark

rss: /atom.xml

# Miscellaneous
google_analytics: 
baidu_analytics: 392796d51567e848aebf813b65cb8656
favicon: /favicon.ico
twitter:

#cover: img/bg6.jpg
cover: 
slogan: "dont count the days, make the days count"
