menu:
  - title: 首页
    url:
    intro: ""
    icon: "fa fa-home"
  - title: 存档
    url: archives
    intro: ""
    icon: "fa fa-list"
  - title: 关于
    url: about
    intro: ""
    icon: "fa fa-info-circle"
  - title: RSS
    url: atom.xml
    intro: "这是一个订阅源"
    icon: "fa fa-rss"

links:
  - title: "GitHub"
    url: http://www.github.com/wayou
    intro: "码农之家"
    icon: "fa fa-github"
  - title: "微博"
    url: http://www.weibo.com/liuwayong
    intro: "twitter的本地化版本"
    icon: "fa fa-weibo"

widgets:
- recent_posts
- links

rss:
favicon: favicon.ico
google_analytics:
baidu_analytics: 392796d51567e848aebf813b65cb8656
footer: ""
