name: generate my blog posts
on:
  issues:
    types: [opened, edited]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wayou/turn-issues-to-posts-action@v1.2.2
        with:
          branch: "master"
          dir: "_posts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          created_at: ${{ github.event.issue.created_at }}
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          actor: ${{ github.actor }}
